# Generated by Django 5.1.1 on 2024-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_alter_recipe_options_recipe_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/uploaded/"
            ),
        ),
    ]
